services:
  - type: web
    name: django-rest-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_rest_auth.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: django_rest_auth.settings
      - key: ALLOWED_HOSTS
        value: "render.com"
